Jm/omoo test
openEDI/oedisi-example pull request #51
Opened 2023-12-20 21:35 UTC by tarekelgindy

2024-01-09 17:53 UTC, josephmckinsey requested changes

2024-01-09 17:53 UTC, josephmckinsey commented on LocalFeeder/FeederSimulator.py
> +            import pdb;pdb.set_trace()
This is probably not needed. P.S. Use --pdb in pytest to automatically enter debug mode on failure.

2024-01-09 17:53 UTC, josephmckinsey commented on LocalFeeder/FeederSimulator.py
> +
Nit: maybe run a formatter to remove these lines

2024-01-09 17:53 UTC, josephmckinsey commented on LocalFeeder/tests/test_feeder.py
> +
I think we talked about this, but could we check that the pv is actually set there using a solve + getting the power injections.

2024-01-17 17:24 UTC, josephmckinsey approved these changes
Might want to run black or ruff on FeederSimulator.py

2024-01-17 17:24 UTC, josephmckinsey commented on LocalFeeder/FeederSimulator.py
> +                print(dss.PVsystems.Name())
Do we want to keep this print?

2024-01-17 17:24 UTC, josephmckinsey commented on LocalFeeder/FeederSimulator.py
> +                print(dss.PVsystems.Name())
print again?

2024-01-17 18:27 UTC, tarekelgindy commented on LocalFeeder/FeederSimulator.py
> +                print(dss.PVsystems.Name())
Ok I'll get rid of these.

2024-01-17 18:47 UTC, merged